---
title: "Assignment1"
author: "Merve Özen Þahin"
date: "16 Ekim 2018"
output: html_document
---


## Assignment: Find Three R Examples about My Work
I am working at Central Bank of Republic of Turkey as a Data Architect.
I am responsible for database design standards, deployment and integration processes.


## Example 1: R for Data Cleaning
R is a great choice for manipulating, cleaning, summarizing, producing probability statistics, and so on. In addition, it's not going away anytime soon, it is platform independent, so what you create will run almost anywhere, and it has awesome help resources.

R is a language and environment that is easy to learn, very flexible in nature, and very focused on statistical computing, making it a great choice for manipulating, cleaning, summarizing, producing probability statistics, and so on.

In addition, here are a few more reasons to use R for data cleaning:

It is used by a large number of data scientists so it's not going away anytime soon. R is platform independent, so what you create will run almost anywhere. R has awesome help resources.

+ [Link1](https://www.youtube.com/watch?v=I8XWImTp8VE&list=RDI8XWImTp8VE&start_radio=1)
+ [Link2](https://www.datacamp.com/community/blog/an-introduction-to-cleaning-data-in-r)

## Example 2: R for Predicting Value of Transactions (Banking)
The aim of this challenge is to predict the “value of transactions for each potential customer” based on customer data provided by the Santander Bank. More specifically, the bank wants us to predict the “value of the customer’s transaction” before it occurs. The goal is to provide tailored financial service based on this prediction. This is the 3rd time that the Santander Group is requesting the help of the Kaggle community.

+ [Link](https://www.kaggle.com/headsortails/breaking-bank-santander-eda)

## Example 3: R for Recommendation Engine
How do we make recommendations in our lives ? We do it based on our past experiences. Now imagine, what if we start making instant recommendations based on data in our real lives? First, we’ll feel like an intelligent adviser. Second, we will no longer be humans. Therefore, we aim to build intelligent softwares, which are capable of providing cogent recommendations.
+ [Link1](https://www.analyticsvidhya.com/blog/2016/03/exploring-building-banks-recommendation-system/)
+ [Link2](https://www.youtube.com/watch?v=R6jaYdBNHFc)
